# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format - you can use {branch} name in version format too
version: 0.3.1.{build}-{branch}

branches:
  except:
  - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012


#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
- x86
- x64
- Any CPU

build:
  # enable MSBuild parallel builds
  parallel: true
  # path to Visual Studio solution or project
  project: telemetry-update-removal\telemetry-update-removal.sln
  # MSBuild verbosity level
  verbosity: normal

test:
  categories:
    except:
    - NotForAppVeyor
